### ISSUE TITLE
Comment config-files

### ISSUE THREAD

**Issue by NFiedler** [bit-bots/bitbots_vision#1]
Config files need more comments describing every parameters effect.

**Comment by NFiedler** [comment]
We should use the option to separate groups into tabs, too.

**Comment by JanGut** [comment]
Separation of groups into tabs is already done with: d8fcc563f960395c17c060803d962bc17a5a7eff.

**Comment by NFiedler** [comment]
Is this done in #107 ???

**Comment by JanGut** [comment]
No, since I still need to merge this description into the yaml config file. Hopefully this will be done by tomorrow morning...
