### ISSUE TITLE
Try out Praktikum 2018 LineDetector

### ISSUE THREAD

**Issue by Flova** [bit-bots/bitbots_vision#112]
Copy from the old gogs repo.

**Comment by NFiedler** [comment]
I think we should close this as that approach was looking for whole lines and we want some kind of mask.

**Comment by Flova** [comment]
Okay

**Comment by JanGut** [comment]
What does okay mean?

**Comment by timonegk** [comment]
@JanGut it was in reference to @Nfiedlers comment that has disappeared: I think we should close this as that approach was looking for whole lines and we want some kind of mask.

**Comment by JanGut** [comment]
Okay, thank you for the clarification.
