### ISSUE TITLE
Create a launchfile to create ROSbags

### ISSUE THREAD

**Issue by Flova** [bit-bots/bitbots_vision#113]
> With a launchfile which is able to start the camera node and remapping of the image or even to automatically start the recording of a bag would make ROSbag recordings easier as any bitbot has ever seen!
~ @NFiedler on gogs

**Comment by JanGut** [comment]
Isn't this already done with 4050b54?

**Comment by Flova** [comment]
Currently this only supports the Logitech camera. We should add a basler parameter too.
