### ISSUE TITLE
Rename image_raw message

### ISSUE THREAD

**Issue by jaagut** [bit-bots/bitbots_vision#123]
@SammyRamone mentioned, we should rename our `image_raw` topic to something like `image_proc` since it is not raw anymore...
For backwards compatibility (e.g. for rosbags), we could write a little script, which remaps the topic.

**Comment by JanGut** [comment]
Is this still relevant?
What are your opinions to this issue? @NFiedler @Flova @johagge @hendrikbrandt

**Comment by Flova** [comment]
Should be adressed in my opinion. The used image is def. not an raw image.

**Comment by NFiedler** [comment]
I'd be fine with both.

**Comment by JanGut** [comment]
Okay, I also prefer renaming this.

**Comment by JanGut** [comment]
Add toplevel topic `/camera/`
