### ISSUE TITLE
Treshold in Yolo Handler

### ISSUE THREAD

**Issue by johagge** [bit-bots/bitbots_vision#151]
The threshold is inconsistent in the Yolo Handler.

First: The opencv handler does not use use the parameter ("ball_candidate_rating_threshold") specified in the config, but uses a static threshold of 0.5

Secondly: It defines a "self._confidence_threshold = 0.5".
In predict() it ignores this parameter:                     
\# Static threshold
if confidence > 0.5:

and then uses the self._confidence_threshold in the computation for the NMSBoxes again.

Third: I am not sure about this, but I assume the NMSBoxes function would filter out any candidates below the threshold anyway, so do we check twice with no benefit?

**Comment by timonegk** [comment]
Closed in #185.
