### ISSUE TITLE
tf collector

### ISSUE THREAD

**Issue by JanGut** [bit-bots/bitbots_vision#157]
In vision tools, there is the file [tf_collector.py](https://github.com/bit-bots/bitbots_vision/blob/master/bitbots_vision_tools/src/tf_collector.py) which was initially used for davros and migrated from gogs to github.
This file has absolutlly no relation to the rest of the vision pipeline.

I suggest to delete the file, if it is not needed anymore or to move this into a more suitable repo.

**Comment by jgueldenstein** [comment]
I think we can delete this
