### ISSUE TITLE
Reduce usage of print

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_vision#17]
Currently, `print` is used in the live_classifier and live_fcnn_03 files. The debug printer should be used instead.

**Comment by hendrikbrandt** [comment]
For now the occurrences of print have bin replaced by logging with different verbosity levels. Therefore the debug printer may be obsolete and has to be reevaluated.

**Comment by timonegk** [comment]
The obsolescence of the debug printer is actually more related to #18
