### ISSUE TITLE
Use ROS named loggers instead of debug printer

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_vision#18]
Currently, the vision debug printer just reimplements the actual ROS named loggers. You can provide a logger name like this: `rospy.logdebug('message', logger_name='field_boundary_detector')`. All logged messages will be shown and can be filtered int the rqt log console and the logger leven in the actual screen output can be controlled by using the rqt logger level plugin or by calling the `set_logger_level` service. The logger name in the above example would be `/rosout/<node name>/field_boundary_detector`.
Using these loggers would also reduce external dependencies of the modules.

**Comment by NFiedler** [comment]
I strongly support this! This should be done after the existing PR is merged into master (as it will be very hatd to merge otherwise).

**Comment by JanGut** [comment]
This is now resolved with #108.
