### ISSUE TITLE
Field boundary detector: Restep for downsampling detector

### ISSUE THREAD

**Issue by Flova** [bit-bots/bitbots_vision#180]
## Is your feature request related to a problem? Please describe.
The downsampling field boundary detector has the tendency to overshoot and leave a gap between the detected and real boundary. This is caused by the bluring.

## Describe the solution you'd like
For the downsampling field boundary detector, we should add some kind of "restep size" to step back and reduce the overshooting of this method.

**Comment by jaagut** [comment]
Should this be a constant "restep size" or e.g. depending on the slope of the field boundary in that point?

**Comment by Flova** [comment]
No it should depend on the amount of smoothing that was set and that introduces the overstepping.
