### ISSUE TITLE
Vision: Use rospy.rate

### ISSUE THREAD

**Issue by jaagut** [bit-bots/bitbots_vision#216]
## Describe the solution you'd like
Instead of looping with time, we could use rospy.rate as can be seen in the localization.
This applies to the `vision.py` as well as `dynamic_color_space.py`.

**Comment by Flova** [comment]
Are there loops that use a time control in the vision?!? I think w only use callbacks.

**Comment by Flova** [comment]
Ping

**Comment by Flova** [comment]
Ping @JanGut

**Comment by JanGut** [comment]
Yeah, as said in person, in line https://github.com/bit-bots/bitbots_vision/blob/c83e71be29634e0f47c1b84076ce8507352d7bbb/bitbots_vision/src/bitbots_vision/vision.py#L134
