### ISSUE TITLE
Integrate Basler camera

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_vision#22]
* driver ✓
* launch file
* adapt camera calibration (see https://github.com/bit-bots/wolves_image_provider/issues/2)
* make everything work

**Comment by timonegk** [comment]
* driver: in private git, integrated in install script
* launch file: see #32 
* camera calibration: default in private git, per robot file still missing
* make everything work: some issues in head behavior remain currently (see pull requests there)

**Comment by Flova** [comment]
All stuff for the Basler Camera seems to be completed and tested on the robot, so I think this issue can be closed.

**Comment by NFiedler** [comment]
#40 is not merged yet.

**Comment by timonegk** [comment]
#40 is merged and everythig seems to work. Camera calibration files exist and the head behavior pull requests were merged.
