### ISSUE TITLE
FieldBoundary: Abstraction between convex and normal field boundary

### ISSUE THREAD

**Issue by jaagut** [bit-bots/bitbots_vision#222]
## Is your feature request related to a problem? Please describe.
The FieldBoundaryDetector creates a field boundary and a convex field boundary.
This should be decoupled.
This as also necessary for further changes.

## Describe the solution you'd like
Some abstract classes and a little bit of inheritance...

**Comment by jaagut** [comment]
This is not necessary anymore.

**Comment by Flova** [comment]
Why? @jaagut
