### ISSUE TITLE
YOLO: prevent overfitting

### ISSUE THREAD

**Issue by johagge** [bit-bots/bitbots_vision#225]
## Is your feature request related to a problem? Please describe.

Currently the amount of iterations the YOLO was trained on is not properly evaluated.
This could mean our network could be overfitted.
## Describe the solution you'd like

To avoid this we should follow the steps descriped in the darknet repo, and also evaluate saving the weights more often than just every 1000 steps.

**Comment by Flova** [comment]
I trained the yolo and evaluated that the tiny yolo does not overfit on our amount of training data because the model size is to small and the dataset is very large.
