### ISSUE TITLE
FCNN evaluation with new camera 

### ISSUE THREAD

**Issue by NFiedler** [bit-bots/bitbots_vision#24]
The FCNN has to be evaluated with the new camera. Possibly, a blur has to be added. This issue is related to #23, #22 and #20.

**Comment by Daniel451** [comment]
Do we already have a sophisticated (test?!) dataset for the new camera? If not, this should be the first.

**Comment by Flova** [comment]
I think this issue can be closed. @timonegk trained the model with the latest data from the new camera and it works pretty well on the robot.
