### ISSUE TITLE
Dynamic colorspace uses 100% cpu

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_vision#246]
## Expected behavior
The dynamic colorspace should take a reasonable amount of cpu.

## Current behavior
The dynamic colorspace uses a whole cpu.

## Steps to Reproduce
1. `roslaunch bitbots_vision vision_startup.launch`

## Context (Environment)
- [ ] RViz
- [ ] Simulator
- [x] Robot
- [x] Local

**Comment by Flova** [comment]
The dyn colorspace has indeed no cap, because the jetson had an unused core for it. We could either add a limit of 1 FPS or something like that or we disable it. I mostly disabled it during testing on the whats your opinion?

**Comment by SammyRamone** [comment]
Well, the dynamic colorspace is there for a reason. I would not want to disable it. Just limiting the FPS would be fine and easy todo. We still have enough CPU power available, it's not like we desperatly need to make room. Currently, it just looks like wasting it
