### ISSUE TITLE
yoeo: TypeError: detect_image() got an unexpected keyword argument 'robot_class_ids'

### ISSUE THREAD

**Issue by val-ba** [bit-bots/bitbots_vision#339]
I started rl bitbots_bringup simulator_teamplayer.launch game_controller:=false and then I got TypeError: detect_image() got an unexpected keyword argument 'robot_class_ids'. 
## Steps to Reproduce

1.
2.
3.
...

## Context (Environment)

- [ ] RViz
- [ ] Simulator
- [ ] Robot
- [ ] Local

**Comment by Flova** [comment]
Try to update YOEO / reinstall the requirements.txt

**Comment by Flova** [comment]
I close this because I think it is a result of an old YOEO version. Feel free to reopen if it is is occuring again.
