### ISSUE TITLE
Reset line point count to default

### ISSUE THREAD

**Issue by JanGut** [bit-bots/bitbots_vision#36]
To save some resources while the RoboCup world championship 2019, the parameter `line_detector_linepoints_range` has been set to `0`.
This parameter determines the number of created line points.

Please reset this afterward to default `200`.

**Comment by JanGut** [comment]
The `line_detector_linepoints_range` value is still 10000. We should evaluate this with default settings in f031 and probably again after we use a localization.

**Comment by Flova** [comment]
See pull request #147

**Comment by Flova** [comment]
See pull request
