### ISSUE TITLE
Find a better name for the function "_obstacle_detector_distance"

### ISSUE THREAD

**Issue by Flova** [bit-bots/bitbots_vision#60]
Referring to a code comment, we should find a better name for the function  "_obstacle_detector_distance".

**Comment by Flova** [comment]
Any suggestions for a better name? @NFiedler @hendrikbrandt

**Comment by jaagut** [comment]
I can not find this code comment and I think, the function name is okay. Therefore I close this issue.
However, there are multiple other TODOs in code comments, that should be resolved...
