### ISSUE TITLE
Evaluate runtime evaluator

### ISSUE THREAD

**Issue by Flova** [bit-bots/bitbots_vision#62]
We should evaluate in which cases we want to use the runtime evaluator in the future. The current solution with the evaluator removed via code comments seems not like a permanent solution. Maybe we enhance it further (with activation via the launch parameter/config) or we use common profiling tools like `profilehooks`.

**Comment by JanGut** [comment]
The runtime evaluator should still exist as a vision module, but all usages could be removed in #59.
